/**
 * campaignMockData.js
 *
 * Centralized mock data repository for SocialPilot Campaigns.
 * Contains mock campaigns for Business clients (clientId-associated) and Content Creators.
 */

const now = Date.now();
const daysAgo = (n) => new Date(now - n * 86400000).toISOString().split('T')[0];
const daysAhead = (n) => new Date(now + n * 86400000).toISOString().split('T')[0];

export const INITIAL_MOCK_CAMPAIGNS = [
  // ── Marketing Client Nike Campaigns ─────────────────────────────────────────
  {
    id: 'cmp-nike-summer',
    name: 'Nike Summer Sale',
    description: 'Promote the seasonal summer footwear and apparel inventory clearance sale.',
    status: 'active',
    startDate: daysAgo(10),
    endDate: daysAhead(20),
    platforms: ['instagram', 'facebook', 'youtube'],
    goals: ['Brand Awareness', 'Engagement', 'Product Promotion'],
    progress: 68,
    totalPosts: 12,
    scheduledPosts: 5,
    publishedPosts: 4,
    draftPosts: 3,
    clientId: 'nike',
    ownerId: null,
    assignedPosts: [
      { id: 'pst-01', caption: 'Step into summer with the new Air Max collection 👟🌴', platform: 'instagram', status: 'scheduled', scheduledTime: '2026-07-25 18:00' },
      { id: 'pst-02', caption: 'Summer sale up to 40% off starts this Friday. Mark your calendars!', platform: 'facebook', status: 'scheduled', scheduledTime: '2026-07-24 09:00' },
      { id: 'pst-03', caption: 'Refreshed classic styles for hot sunny days. Free shipping!', platform: 'instagram', status: 'published', scheduledTime: '2026-07-20 12:00' },
    ],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  {
    id: 'cmp-nike-running',
    name: 'Run the World 2026',
    description: 'A global digital campaign promoting the Nike Running App and run clubs.',
    status: 'active',
    startDate: daysAgo(5),
    endDate: daysAhead(40),
    platforms: ['instagram', 'youtube'],
    goals: ['Engagement', 'Community Growth'],
    progress: 42,
    totalPosts: 15,
    scheduledPosts: 6,
    publishedPosts: 3,
    draftPosts: 6,
    clientId: 'nike',
    ownerId: null,
    assignedPosts: [
      { id: 'pst-04', caption: 'Join the global movement. Start your running journey today.', platform: 'facebook', status: 'scheduled', scheduledTime: '2026-07-26 10:00' },
    ],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
  },
  {
    id: 'cmp-nike-airmax',
    name: 'Air Max Anniversary',
    description: 'Anniversary campaign highlighting classic and vintage Air Max legacy designs.',
    status: 'planning',
    startDate: daysAhead(15),
    endDate: daysAhead(45),
    platforms: ['instagram', 'facebook', 'linkedin', 'youtube'],
    goals: ['Brand Awareness', 'Lead Generation'],
    progress: 10,
    totalPosts: 20,
    scheduledPosts: 2,
    publishedPosts: 0,
    draftPosts: 18,
    clientId: 'nike',
    ownerId: null,
    assignedPosts: [],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },

  // ── Marketing Client Puma Campaigns ─────────────────────────────────────────
  {
    id: 'cmp-puma-faster',
    name: 'Puma Forever Faster',
    description: 'Global brand campaign highlighting sport performance gear & track athletes.',
    status: 'active',
    startDate: daysAgo(15),
    endDate: daysAhead(15),
    platforms: ['instagram', 'x'],
    goals: ['Brand Awareness', 'Engagement'],
    progress: 85,
    totalPosts: 10,
    scheduledPosts: 2,
    publishedPosts: 7,
    draftPosts: 1,
    clientId: 'puma',
    ownerId: null,
    assignedPosts: [],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },

  // ── Creator Prabhas Campaigns ───────────────────────────────────────────────
  {
    id: 'cmp-cr-baahubali',
    name: 'Baahubali 3 Promotion',
    description: 'Promotional countdown activities and teaser trailers launch strategy for Baahubali 3 movie.',
    status: 'active',
    startDate: daysAgo(5),
    endDate: daysAhead(10),
    platforms: ['instagram', 'facebook', 'youtube'],
    goals: ['Brand Awareness', 'Engagement', 'Product Promotion'],
    progress: 75,
    totalPosts: 15,
    scheduledPosts: 5,
    publishedPosts: 8,
    draftPosts: 2,
    clientId: null,
    ownerId: 'creator-user-id',
    assignedPosts: [
      { id: 'pst-c1', caption: 'Baahubali 3 first look tease! Re-entering the kingdom of Mahishmati ⚔️👑', platform: 'instagram', status: 'scheduled', scheduledTime: '2026-07-25 10:00' },
      { id: 'pst-c2', caption: 'Official full-length cinematic teaser release on YouTube channel tomorrow!', platform: 'youtube', status: 'scheduled', scheduledTime: '2026-07-23 15:00' },
    ],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: 'cmp-cr-salaar',
    name: 'Salaar Promotion',
    description: 'Behind the scenes release snippets and official stunt crew interviews.',
    status: 'active',
    startDate: daysAgo(12),
    endDate: daysAhead(25),
    platforms: ['instagram', 'x', 'youtube'],
    goals: ['Engagement', 'Website Traffic'],
    progress: 45,
    totalPosts: 12,
    scheduledPosts: 4,
    publishedPosts: 5,
    draftPosts: 3,
    clientId: null,
    ownerId: 'creator-user-id',
    assignedPosts: [
      { id: 'pst-c3', caption: 'Behind the scenes of Salaar stunts. Stunt coordinator walkthrough 🎬🔥', platform: 'youtube', status: 'ready', scheduledTime: '2026-07-22 14:30' },
    ],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
  },
  {
    id: 'cmp-cr-brandcollab',
    name: 'Brand Collaboration',
    description: 'Sponsorship content series displaying designer clothing lines.',
    status: 'active',
    startDate: daysAgo(4),
    endDate: daysAhead(4),
    platforms: ['instagram', 'linkedin'],
    goals: ['Product Promotion', 'Lead Generation'],
    progress: 90,
    totalPosts: 8,
    scheduledPosts: 1,
    publishedPosts: 7,
    draftPosts: 0,
    clientId: null,
    ownerId: 'creator-user-id',
    assignedPosts: [],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
];
