"""Add analytics tables

Revision ID: 0688ca68eb96
Revises: 27fc9b5faefa
Create Date: 2026-08-05 21:09:39.131803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0688ca68eb96'
down_revision: Union[str, Sequence[str], None] = '27fc9b5faefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('new_followers', sa.Integer(), nullable=False),
    sa.Column('lost_followers', sa.Integer(), nullable=False),
    sa.Column('gender_distribution', sa.JSON(), nullable=True),
    sa.Column('age_distribution', sa.JSON(), nullable=True),
    sa.Column('country_distribution', sa.JSON(), nullable=True),
    sa.Column('city_distribution', sa.JSON(), nullable=True),
    sa.Column('most_active_hours', sa.JSON(), nullable=True),
    sa.Column('most_active_days', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_analytics_platform'), ['platform'], unique=False)

    op.create_table('platform_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_analytics_platform'), ['platform'], unique=True)

    op.create_table('campaign_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_analytics_campaign_id'), ['campaign_id'], unique=True)

    op.create_table('post_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'platform', name='uq_post_platform_analytics')
    )
    with op.batch_alter_table('post_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_analytics_post_id'), ['post_id'], unique=False)

    bind = op.get_bind()
    inspector = inspect(bind)
    metrics_cols = [c['name'] for c in inspector.get_columns('analytics_metrics')]
    reports_cols = [c['name'] for c in inspector.get_columns('reports')]
    reports_indexes = [idx['name'] for idx in inspector.get_indexes('reports')]
    reports_fks = [fk['name'] for fk in inspector.get_foreign_keys('reports')]

    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        for col in ['saves', 'last_synced', 'engagement_rate', 'clicks']:
            if col in metrics_cols:
                batch_op.drop_column(col)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        if 'ix_reports_campaign_id' in reports_indexes:
            batch_op.drop_index(batch_op.f('ix_reports_campaign_id'))
        if 'reports_campaign_id_fkey' in reports_fks:
            batch_op.drop_constraint(batch_op.f('reports_campaign_id_fkey'), type_='foreignkey')
        for col in ['download_count', 'export_format', 'selected_filters', 'file_location', 'campaign_id', 'report_type']:
            if col in reports_cols:
                batch_op.drop_column(col)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    metrics_cols = [c['name'] for c in inspector.get_columns('analytics_metrics')]
    reports_cols = [c['name'] for c in inspector.get_columns('reports')]
    reports_indexes = [idx['name'] for idx in inspector.get_indexes('reports')]
    reports_fks = [fk['name'] for fk in inspector.get_foreign_keys('reports')]

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        if 'report_type' not in reports_cols:
            batch_op.add_column(sa.Column('report_type', sa.VARCHAR(length=50), server_default=sa.text("'''engagement'''::character varying"), autoincrement=False, nullable=False))
        if 'campaign_id' not in reports_cols:
            batch_op.add_column(sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True))
        if 'file_location' not in reports_cols:
            batch_op.add_column(sa.Column('file_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        if 'selected_filters' not in reports_cols:
            batch_op.add_column(sa.Column('selected_filters', sa.TEXT(), autoincrement=False, nullable=True))
        if 'export_format' not in reports_cols:
            batch_op.add_column(sa.Column('export_format', sa.VARCHAR(length=20), server_default=sa.text("'''pdf'''::character varying"), autoincrement=False, nullable=False))
        if 'download_count' not in reports_cols:
            batch_op.add_column(sa.Column('download_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        if 'reports_campaign_id_fkey' not in reports_fks:
            batch_op.create_foreign_key(batch_op.f('reports_campaign_id_fkey'), 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
        if 'ix_reports_campaign_id' not in reports_indexes:
            batch_op.create_index(batch_op.f('ix_reports_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        if 'clicks' not in metrics_cols:
            batch_op.add_column(sa.Column('clicks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        if 'engagement_rate' not in metrics_cols:
            batch_op.add_column(sa.Column('engagement_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        if 'last_synced' not in metrics_cols:
            batch_op.add_column(sa.Column('last_synced', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        if 'saves' not in metrics_cols:
            batch_op.add_column(sa.Column('saves', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('post_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_analytics_post_id'))

    op.drop_table('post_analytics')
    with op.batch_alter_table('campaign_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_analytics_campaign_id'))

    op.drop_table('campaign_analytics')
    with op.batch_alter_table('platform_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_analytics_platform'))

    op.drop_table('platform_analytics')
    with op.batch_alter_table('audience_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_analytics_platform'))

    op.drop_table('audience_analytics')
    # ### end Alembic commands ###
