"""make_analytics_columns_nullable

Revision ID: 0a732c7abdfa
Revises: 0688ca68eb96
Create Date: 2026-08-07 02:50:55.250047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a732c7abdfa'
down_revision: Union[str, Sequence[str], None] = '0688ca68eb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('publishing_notifications', sa.Boolean(), nullable=False),
    sa.Column('campaign_notifications', sa.Boolean(), nullable=False),
    sa.Column('account_activity_notifications', sa.Boolean(), nullable=False),
    sa.Column('team_collaboration_notifications', sa.Boolean(), nullable=False),
    sa.Column('system_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_frequency', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analytics_available', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('error_reason', sa.Text(), nullable=True))
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('impressions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reactions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('comments',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shares',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('post_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analytics_available', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('error_reason', sa.Text(), nullable=True))
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('comments',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shares',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('saves',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('impressions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('clicks',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('engagement_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_analytics', schema=None) as batch_op:
        batch_op.alter_column('engagement_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('clicks',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('impressions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('saves',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shares',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comments',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('error_reason')
        batch_op.drop_column('analytics_available')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.alter_column('shares',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comments',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reactions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('impressions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('error_reason')
        batch_op.drop_column('analytics_available')

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
