"""add facebook page fields

Revision ID: 317432ea9977
Revises: 0a732c7abdfa
Create Date: 2026-08-16 19:59:40.774392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317432ea9977'
down_revision: Union[str, Sequence[str], None] = '0a732c7abdfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('page_access_token_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('facebook_page_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.drop_column('facebook_page_id')
        batch_op.drop_column('page_access_token_encrypted')
        batch_op.drop_column('page_id')

    # ### end Alembic commands ###
