"""sync_completed_models

Revision ID: 4f24360dd94f
Revises: 8eb1c63d67c2
Create Date: 2026-07-24 00:14:07.795468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f24360dd94f'
down_revision: Union[str, Sequence[str], None] = '8eb1c63d67c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rendered_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('collaboration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('business_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaboration_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaboration_requests_business_user_id'), ['business_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_team_id'), ['team_id'], unique=False)

    op.create_table('analytics_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('reactions', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'platform', name='uq_post_platform_metric')
    )
    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_metrics_post_id'), ['post_id'], unique=False)

    op.create_table('publishing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publishing_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publishing_logs_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publishing_logs_status'), ['status'], unique=False)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_accounts_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_accounts_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))

    with op.batch_alter_table('publishing_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publishing_logs_status'))
        batch_op.drop_index(batch_op.f('ix_publishing_logs_post_id'))

    op.drop_table('publishing_logs')
    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_metrics_post_id'))

    op.drop_table('analytics_metrics')
    with op.batch_alter_table('collaboration_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_team_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_status'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_business_user_id'))

    op.drop_table('collaboration_requests')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_owner_id'))
        batch_op.drop_index(batch_op.f('ix_reports_client_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
