"""Refactor DB architecture with batch mode

Revision ID: 8eb1c63d67c2
Revises: 
Create Date: 2026-07-23 18:01:20.249527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eb1c63d67c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.drop_column('is_draft')
        batch_op.drop_column('timezone')
        batch_op.drop_column('media_file_path')
        batch_op.drop_column('title')
        batch_op.drop_column('publishing_status')
        batch_op.drop_column('scheduled_date')
        batch_op.drop_column('scheduled_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('organization')
        batch_op.drop_column('password')
        batch_op.drop_column('full_name')
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('organization', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_date', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('publishing_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('media_file_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('is_draft', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
