"""Add session_version

Revision ID: a61059912992
Revises: c9f384c6fe0c
Create Date: 2026-08-15 13:02:15.357940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61059912992'
down_revision: Union[str, Sequence[str], None] = 'c9f384c6fe0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_account_ids', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('platform_options', sa.Text(), nullable=False, server_default='{}'))

    with op.batch_alter_table('publishing_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('provider_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_publishing_logs_social_account_id'), ['social_account_id'], unique=False)
        batch_op.create_unique_constraint('uq_publishing_log_attempt', ['post_id', 'platform', 'attempt_number'])
        batch_op.create_foreign_key(None, 'social_accounts', ['social_account_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_account_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_social_accounts_external_account_id'), ['external_account_id'], unique=False)
        batch_op.create_unique_constraint('uq_social_account_identity', ['user_id', 'platform', 'external_account_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_social_account_identity', type_='unique')
        batch_op.drop_index(batch_op.f('ix_social_accounts_external_account_id'))
        batch_op.drop_column('connected_at')
        batch_op.drop_column('last_error')
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('external_account_id')

    with op.batch_alter_table('publishing_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_publishing_log_attempt', type_='unique')
        batch_op.drop_index(batch_op.f('ix_publishing_logs_social_account_id'))
        batch_op.drop_column('duration_ms')
        batch_op.drop_column('attempt_number')
        batch_op.drop_column('provider_response')
        batch_op.drop_column('social_account_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('platform_options')
        batch_op.drop_column('platform_account_ids')

    # ### end Alembic commands ###
